#!/usr/bin/env ruby

####################################################################################################
## INFO:
####################################################################################################

# DESCRIPCIÓN
# =====================
# INTERPRETADOR para el lenguaje Retina.
# Basado en los ejemplos aportados por el preparador David Lilue y siguiendo las
# especificaciones dadas para el proyecto del curso CI-3725 de la Universidad
# Simón Bolívar durante el trimestre Enero-Marzo 2017.

# AUTORES
# =====================
# Carlos Serrada      13-11347    cserradag96@gmail.com
# Mathias San Miguel  13-11310    mathiassanmiguel@gmail.com

# ALCANCE ACTUAL
# =====================
# - Análisis Lexicográfico  :Listo
# - Análisis Sintáctico     :Listo
# - Análisis de Contexto    :Listo
# - Intérprete Final        :Próximamente

# REQUIERE
# =====================
# retina_lexer.rb
# retina_parser.rb (creado a partir de `racc retina_parser.y`)
# retina_ast.rb


####################################################################################################
## LIBRERÍAS:
####################################################################################################

require_relative 'retina_parser'  # Librería que contiene el parser de Retina


####################################################################################################
## DECLRACIÓN DE FUNCIONES:
####################################################################################################

def main
  # LECTURA (chequeo de .ext y abrir como string)
  # ================================
  ARGV[0] =~ /\w+\.rtn/
  if $&.nil?
    puts "Tipo de archivo no reconocido\nPor favor utilice un archivo 'file.rtn'"
    exit 1
  end
  
  begin
    input = File::read(ARGV[0])
  rescue
    puts "No se encontró el archivo"
    exit 1
  end
  
  # Atrapa LEXEMAS
  # ================================
  begin
    ## Análisis lexicográfico previo
    # $row = 1; $col = 1        # Contamos líneas y columnas desde 1
    # lexer = Lexer.new input   # Inicializamos Lexer con el input del archivo
    # while lexer.catch_lexeme; end
    
    begin
      $row = 1; $col = 1        # Contamos líneas y columnas desde 1
      lexer = Lexer.new input   # Inicializamos Lexer con el input del archivo
      parser = Parser.new       # Inicializamos Parser
      ast = parser.parse lexer  # Creamos el AST a partir del output del Parser
      # ast.print_ast           # Imprimimos el AST
      
    rescue SyntacticError => e  # Al primer error de sintáxis salimos corriendo
      puts e
      exit 1
    
    rescue ContextError => e  # Al primer error de sintáxis salimos corriendo
      puts e
      exit 1
      
    else
      # $stt = SymbolMetaTable.new
      # # Añadimos Funciones del sistema a la tabla de símbolos
      # $stt.meta[-1].table += [Row.new("home", "None")]
      # $stt.meta[-1].table += [Row.new("openeye", "None")]
      # $stt.meta[-1].table += [Row.new("closeeye", "None")]
      # $stt.meta[-1].table += [Row.new("forward", "None")]
      # $stt.meta[-1].table += [Row.new("backward", "None")]
      # $stt.meta[-1].table += [Row.new("rotatel", "None")]
      # $stt.meta[-1].table += [Row.new("rotater", "None")]
      # $stt.meta[-1].table += [Row.new("setposition", "None")]
      # $stt.meta[-1].table += [Row.new("arc", "None")]
      begin
        ast.recorrer
      rescue ContextError => e  # Al primer error de sintáxis salimos corriendo
        puts e
        exit 1
      end
    end
  end
end

####################################################################################################
## PROGRAMA PRINCIPAL:
####################################################################################################

main
