#! /usr/bin/ruby

require_relative 'retina_lexer'

def main
  # Check extension
  ARGV[0] =~ /\w+\.rtn/
  if $&.nil?; puts "Tipo de archivo no reconocido\nPor favor utilice un archivo 'file.rtn'"; return; end
  # Open file as a string
  begin
    input = File::read(ARGV[0])
  rescue
    puts "File not found"
    return
  end
  # Create lexer
  $row = 1
  $col = 1
  lexer = Lexer.new input
  # Get tokens until input is empty
  begin
    while lexer.catch_lexeme; end
  end
end

main